bind_port = 8099
bind_host = "0.0.0.0"

token_secret = "secret"

backend = "redis"
redis_urls = "redis://huly.local:6379"
redis_password = "<invalid>"
redis_mode = "direct"
redis_service = "mymaster"

max_ttl = 3600

heartbeat_timeout = 90
ping_timeout = 30

loglevel = "INFO"

# optional settings
# max_size = 100

# permit_file = "/home/user/hulipulse/permit.rego"
