#:schema node_modules/wrangler/config-schema.json
name = "datalake-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

kv_namespaces = [
  { binding = "datalake_blobs", id = "64144eb146fd45febc928d44419ebb39",  preview_id = "31c6f6e76e7e4524a59f87a4f381de82" }
]

r2_buckets = [
  { binding = "DATALAKE_APAC", bucket_name = "datalake-eu-west", preview_bucket_name = "dev-datalake-eu-west" },
  { binding = "DATALAKE_EEUR", bucket_name = "datalake-eu-west", preview_bucket_name = "dev-datalake-eu-west" },
  { binding = "DATALAKE_WEUR", bucket_name = "datalake-eu-west", preview_bucket_name = "dev-datalake-eu-west" },
  { binding = "DATALAKE_ENAM", bucket_name = "datalake-eu-west", preview_bucket_name = "dev-datalake-eu-west" },
  { binding = "DATALAKE_WNAM", bucket_name = "datalake-eu-west", preview_bucket_name = "dev-datalake-eu-west" }
]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "055e968f3067414eaa30467d8a9c5021"
localConnectionString = "postgresql://root:roach@localhost:26257/datalake"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
DATALAKE_EEUR_BUCKET_NAME = "datalake-eeur"
# DATALAKE_EEUR_ACCESS_KEY = ""
# DATALAKE_EEUR_SECRET_KEY = ""
DATALAKE_WEUR_BUCKET_NAME = "datalake-weur"
# DATALAKE_WEUR_ACCESS_KEY = ""
# DATALAKE_WEUR_SECRET_KEY = ""
DATALAKE_APAC_BUCKET_NAME = "datalake-apac"
# DATALAKE_APAC_ACCESS_KEY = ""
# DATALAKE_APAC_SECRET_KEY = ""
DATALAKE_ENAM_BUCKET_NAME = "datalake-enam"
# DATALAKE_ENAM_ACCESS_KEY = ""
# DATALAKE_ENAM_SECRET_KEY = ""
DATALAKE_WNAM_BUCKET_NAME = "datalake-wnam"
# DATALAKE_WNAM_ACCESS_KEY = ""
# DATALAKE_WNAM_SECRET_KEY = ""

# STREAMS_ACCOUNT_ID = ""
# STREAMS_AUTH_KEY = ""
# R2_ACCOUNT_ID = ""


[env.staging]
name = "datalake-worker-staging"

kv_namespaces = [
  { binding = "datalake_blobs", id = "d52f8b6a9a1e495a8d6625d14d8f3188" }
]

r2_buckets = [
  { binding = "DATALAKE_APAC", bucket_name = "datalake-staging-wnam" },
  { binding = "DATALAKE_EEUR", bucket_name = "datalake-staging-wnam" },
  { binding = "DATALAKE_WEUR", bucket_name = "datalake-staging-weur" },
  { binding = "DATALAKE_ENAM", bucket_name = "datalake-staging-wnam" },
  { binding = "DATALAKE_WNAM", bucket_name = "datalake-staging-wnam" }
]

hyperdrive = [
  { binding = "HYPERDRIVE", id = "1f713bb2ec1b464cb663983feca4c89e" }
]

[env.staging.vars]
DATALAKE_EEUR_BUCKET_NAME = "datalake-staging-weur"
DATALAKE_WEUR_BUCKET_NAME = "datalake-staging-wnam"
DATALAKE_APAC_BUCKET_NAME = "datalake-staging-wnam"
DATALAKE_ENAM_BUCKET_NAME = "datalake-staging-wnam"
DATALAKE_WNAM_BUCKET_NAME = "datalake-staging-wnam"

[env.staging.observability]
enabled = true
head_sampling_rate = 1


[env.dev]
name = "datalake-worker-dev"

kv_namespaces = [
  { binding = "datalake_blobs", id = "5acdcea18a504ab3a2d73556314b0047" }
]

r2_buckets = [
  { binding = "DATALAKE_APAC", bucket_name = "datalake-dev" },
  { binding = "DATALAKE_EEUR", bucket_name = "datalake-dev" },
  { binding = "DATALAKE_WEUR", bucket_name = "datalake-dev" },
  { binding = "DATALAKE_ENAM", bucket_name = "datalake-dev" },
  { binding = "DATALAKE_WNAM", bucket_name = "datalake-dev" }
]

hyperdrive = [
  { binding = "HYPERDRIVE", id = "055e968f3067414eaa30467d8a9c5021" }
]

[env.dev.vars]
DATALAKE_EEUR_BUCKET_NAME = "datalake-dev"
DATALAKE_WEUR_BUCKET_NAME = "datalake-dev"
DATALAKE_APAC_BUCKET_NAME = "datalake-dev"
DATALAKE_ENAM_BUCKET_NAME = "datalake-dev"
DATALAKE_WNAM_BUCKET_NAME = "datalake-dev"

[env.dev.observability]
enabled = true
head_sampling_rate = 1
